version: "2"
services:
  elasticsearch-service:
    image: elasticsearch:latest
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - stack

  logstash-service:
    image: logstash:latest
    volumes:
      - /var/log/logstash:/var/log/logstash
    ports:
      - 5043:5043
    environment:
      - xpack.monitoring.enabled=false
    depends_on:
      - elasticsearch-service
    networks:
      - stack

  filebeat-service:
    image: filebeat:latest
    volumes:
      - /var/log/petclinic:/var/log/petclinic
    networks:
      - stack
    depends_on:
      - logstash-service

  metricbeat-system-service:
    image: metricbeat-system:latest
    volumes:
      - /proc:/hostfs/proc:ro 
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro 
      - /:/hostfs:ro 
    network_mode: "host"
    depends_on:
      - logstash-service
      - elasticsearch-service

  kibana-service:
    image: kibana:latest
    ports:
      - "5601:5601"
    networks:
      - stack
    depends_on:
      - elasticsearch-service

volumes:
  esdata:
    driver: local

networks:
  stack:
