version: "2"
services:
  elasticsearch-service:
    image: elasticsearch:latest
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - stack

  logstash-service:
    image: logstash:latest
    environment:
      - xpack.monitoring.enabled=false
    depends_on:
      - elasticsearch-service
    networks:
      - stack

  filebeat-service:
    image: filebeat:latest
    volumes:
      - /var/log/filebeat:/var/log/filebeat
    networks:
      - stack
    depends_on:
      - logstash-service

  spring-petclinic:
    image: spring-petclinic:latest
    volumes:
      - /var/log/filebeat:/var/log/filebeat
    networks:
      - stack

  kibana-service:
    image: kibana:latest
    ports:
      - "5601:5601"
    networks:
      - stack
    depends_on:
      - elasticsearch-service

volumes:
  esdata:
    driver: local

networks:
  stack:
